version = 1

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "secrets"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Tbeakl/WhatsAppAnalysis"

[[transformers]]
name = "gofmt"
enabled = true